bin - formatting

diff --git a/bin/copy b/bin/copy
--- a/bin/copy
+++ b/bin/copy
@@ -4,14 +4,14 @@ set -u
 set -o pipefail
 
 if hash pbcopy 2>/dev/null; then
-	cmd='pbcopy'
+  cmd='pbcopy'
 elif hash wl-copy 2>/dev/null; then
-	cmd='wl-copy'
+  cmd='wl-copy'
 elif hash xclip 2>/dev/null; then
-	cmd='xclip -selection clipboard'
+  cmd='xclip -selection clipboard'
 else
-	echo 'cannot find a copy program' >&2
-	exit 1
+  echo 'cannot find a copy program' >&2
+  exit 1
 fi
 
 exec perl -pe 'chomp if eof' | $cmd
diff --git a/bin/pasta b/bin/pasta
--- a/bin/pasta
+++ b/bin/pasta
@@ -4,12 +4,12 @@ set -u
 set -o pipefail
 
 if hash pbpaste 2>/dev/null; then
-	exec pbpaste
+  exec pbpaste
 elif hash wl-paste 2>/dev/null; then
-	exec wl-paste
+  exec wl-paste
 elif hash xclip 2>/dev/null; then
-	exec xclip -selection clipboard -o
+  exec xclip -selection clipboard -o
 else
-	echo 'cannot find a paste program' >&2
-	exit 1
+  echo 'cannot find a paste program' >&2
+  exit 1
 fi
